# Generated by Django 3.1.7 on 2021-04-13 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0001_initial'),
        ('discussion', '0003_auto_20210413_1506'),
        ('favorites', '0002_auto_20210413_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritesmodel',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion.discussionmodel'),
        ),
        migrations.AlterField(
            model_name='favoritesmodel',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='woolnews_app.postmodel'),
        ),
    ]
