# Generated by Django 3.1.7 on 2021-04-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
