# Generated by Django 3.1.7 on 2021-04-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
