# Generated by Django 3.1.7 on 2021-04-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='sources',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
