# Generated by Django 3.1.6 on 2021-04-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0002_auto_20210408_0158'),
        ('woolnews_app', '0002_postmodel_img'),
    ]

    operations = [
    ]
