# Generated by Django 3.1.7 on 2021-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_auto_20210413_1506'),
        ('woolnews_app', '0002_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='support',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='favs',
            field=models.ManyToManyField(blank=True, to='favorites.FavoritesModel'),
        ),
    ]
