# Generated by Django 3.1.7 on 2021-04-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0003_auto_20210413_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='genre',
            field=models.CharField(choices=[('AT', 'Automotive'), ('SP', 'Sports'), ('AR', 'Arts'), ('PL', 'Politics'), ('CC', 'Climate Change'), ('OP', 'Opinion'), ('DJ', 'DadJokes'), ('GEN', 'General')], default='GEN', max_length=3),
        ),
        migrations.DeleteModel(
            name='GenreModel',
        ),
    ]
