# Generated by Django 3.1.7 on 2021-04-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0003_merge_20210409_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
