# Generated by Django 3.1.6 on 2021-04-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0004_commentmodel_votes'),
        ('woolnews_app', '0004_auto_20210411_0306'),
    ]

    operations = [
    ]
