# Generated by Django 3.1.7 on 2021-04-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0004_auto_20210414_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='likes',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
