# Generated by Django 3.1.7 on 2021-04-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0005_merge_20210411_0339'),
        ('woolnews_app', '0003_merge_20210408_1512'),
    ]

    operations = [
    ]
