# Generated by Django 3.1.6 on 2021-04-12 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0001_initial'),
        ('woolnews_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmodel',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='woolnews_app.CommentModel'),
        ),
        migrations.AddField(
            model_name='discussionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
