<<<<<<< HEAD:discussion/migrations/0002_auto_20210418_0403.py
# Generated by Django 3.1.7 on 2021-04-18 04:03
=======
# Generated by Django 3.2 on 2021-04-16 17:15
>>>>>>> 023042649ddeb25992f18cddfc79e55d4e7a8d87:discussion/migrations/0002_initial.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:discussion/migrations/0002_auto_20210418_0403.py
=======
        ('discussion', '0001_initial'),
>>>>>>> 023042649ddeb25992f18cddfc79e55d4e7a8d87:discussion/migrations/0002_initial.py
        ('favorites', '0001_initial'),
        ('woolnews_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmodel',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='woolnews_app.CommentModel'),
        ),
        migrations.AddField(
            model_name='discussionmodel',
            name='favs',
            field=models.ManyToManyField(blank=True, null=True, to='favorites.FavoritesModel'),
        ),
        migrations.AddField(
            model_name='discussionmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woolnews_app.postmodel'),
        ),
        migrations.AddField(
            model_name='discussionmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
