# Generated by Django 3.1.7 on 2021-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20210413_1453'),
        ('discussion', '0002_auto_20210413_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionmodel',
            name='likes',
        ),
        migrations.AddField(
            model_name='discussionmodel',
            name='favs',
            field=models.ManyToManyField(blank=True, null=True, to='favorites.FavoritesModel'),
        ),
    ]
