# Generated by Django 3.1.7 on 2021-04-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_discussionmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmodel',
            name='body',
            field=models.CharField(default=True, max_length=300),
        ),
    ]
