# Generated by Django 3.1.7 on 2021-04-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_discussionmodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionmodel',
            name='body',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
