# Generated by Django 3.1.7 on 2021-04-12 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('woolnews_app', '0005_merge_20210411_0339'),
        ('discussion', '0004_auto_20210408_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmodel',
            name='comments',
            field=models.ManyToManyField(to='woolnews_app.CommentModel'),
        ),
        migrations.AddField(
            model_name='discussionmodel',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='discussionmodel',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
